djangoProject/djangoProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('sale_management/', include(('sale_management.urls', 'sale_management'), namespace='sale_management')),
]

djangoProject/sale_management/urls.py
from django.urls import path

from sale_management.views import employee, order

urlpatterns = [
    # path('employee/<int:employee_id>/', employee.detail, name='employee_detail'),
    path('employee/<int:pk>/', employee.DetailView.as_view(), name='employee_detail'),
    path('employee/', employee.ListingView.as_view(), name='employee_listing'),

    path('order/<int:pk>/', order.DetailView.as_view(), name='order_detail'),
    # path('order/', order.listing, name='order_listing'),
    path('order/', order.ListingView.as_view(), name='order_listing'),
]

djangoProject/sale_management/models.py
from django.db import models
from django.contrib.auth.models import User


class CreatedAbstractModel(models.Model):
    created_by = models.ForeignKey(
        User,
        blank=True, null=True, on_delete=models.SET_NULL,
        related_name='%(app_label)s_%(class)s_created_by'
    )
    created_at = models.DateTimeField(
        blank=True, null=True, auto_now_add=True,
        db_index=True
    )

    class Meta:
        abstract = True


class ModifiedAbstractModel(models.Model):
    modified_by = models.ForeignKey(
        User,
        blank=True, null=True, on_delete=models.SET_NULL,
        related_name='%(app_label)s_%(class)s_modified_by'
    )
    modified_at = models.DateTimeField(
        blank=True, null=True, auto_now=True,
        db_index=True
    )

    class Meta:
        abstract = True


class TrackingAbstractModel(CreatedAbstractModel, ModifiedAbstractModel):
    class Meta:
        abstract = True


class Employee(TrackingAbstractModel):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100)
    address = models.CharField(max_length=500)
    dob = models.DateField(null=True)  # date of birth

    def __str__(self):
        return f'{self.id} - {self.name}'


class Customer(TrackingAbstractModel):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=150)
    contact_name = models.CharField(max_length=100)
    address = models.CharField(max_length=500)
    phone = models.CharField(max_length=20)

    def __str__(self):
        return f'{self.id} - {self.name} - {self.phone}'

    def save_name(self):
        self.name = self.name.upper()
        self.save()


class Product(TrackingAbstractModel):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100)
    price = models.FloatField()
    quantity = models.IntegerField()

    def __str__(self):
        return f'{self.id} - {self.name}'


class Order(TrackingAbstractModel):
    id = models.AutoField(primary_key=True)
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE)
    purchase_date = models.DateTimeField()
    delivery_date = models.DateField(null=True)

    def __str__(self):
        return f'{self.id} - {self.customer} - {self.employee}'


class OrderDetail(TrackingAbstractModel):
    id = models.AutoField(primary_key=True)
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    price = models.FloatField()
    quantity = models.IntegerField()

    def __str__(self):
        return f'{self.id} - {self.order} - {self.product}'

    @property
    def subtotal(self):
        return self.quantity * self.price

djangoProject/sale_management/views.py
from django.http import HttpResponse, Http404
from django.template import loader
from django.shortcuts import render, get_object_or_404
from sale_management.models import Employee


def detail(request, employee_id):
    # try:
    #     employee = Employee.objects.get(pk=employee_id)
    # except Employee.DoesNotExist:
    #     raise Http404("Employee does not exist")
    # return HttpResponse(employee)
    employee = get_object_or_404(Employee, pk=employee_id)
    return render(request, 'sale_management/employee/detail.html', {'employee': employee})


def listing(request):
    latest_employee_list = Employee.objects.order_by('-created_at')[:3]
    context = {
        'latest_employee_list': latest_employee_list,
    }
    # template = loader.get_template('sale_management/employee/index.html')
    # return HttpResponse(template.render(context, request))
    return render(request, 'sale_management/employee/index.html', context)

djangoProject/sale_management/views/employee.py
from django.http import HttpResponse, Http404
from django.template import loader
from django.shortcuts import render, get_object_or_404
from sale_management.models import Employee
from django.views import generic


# def detail(request, employee_id):
#     # try:
#     #     employee = Employee.objects.get(pk=employee_id)
#     # except Employee.DoesNotExist:
#     #     raise Http404("Employee does not exist")
#     # return HttpResponse(employee)
#     employee = get_object_or_404(Employee, pk=employee_id)
#     return render(request, 'sale_management/employee/detail.html', {'employee': employee})

class DetailView(generic.DetailView):
    model = Employee
    template_name = 'sale_management/employee/detail.html'


# def listing(request):
#     latest_employee_list = Employee.objects.order_by('-created_at')[:3]
#     context = {
#         'latest_employee_list': latest_employee_list,
#     }
#     # template = loader.get_template('sale_management/employee/index.html')
#     # return HttpResponse(template.render(context, request))
#     return render(request, 'sale_management/employee/index.html', context)

class ListingView(generic.ListView):
    template_name = 'sale_management/employee/index.html'
    context_object_name = 'latest_employee_list'

    def get_queryset(self):
        return Employee.objects.order_by('-created_at')[:3]

djangoProject/sale_management/views/order.py
from django.shortcuts import render, get_object_or_404
from sale_management.models import Order, OrderDetail
from django.views import generic


# def detail(request, order_id):
#     order = get_object_or_404(Order, pk=order_id)
#     context = {
#         'order': order,
#         'details': order.orderdetail_set.all()
#     }
#     return render(request, 'sale_management/order/detail.html', context)

class DetailView(generic.DetailView):
    model = Order
    template_name = 'sale_management/order/detail.html'


# def listing(request):
#     orders = Order.objects.order_by('-created_at')[:3]
#     context = {
#         'orders': orders
#     }
#     return render(request, 'sale_management/order/index.html', context)

class ListingView(generic.ListView):
    template_name = 'sale_management/order/index.html'
    context_object_name = 'orders'

    def get_queryset(self):
        return Order.objects.order_by('-created_at')[:3]

djangoProject/templates/sale_management/employee/detail.html
<h1>{{ employee.name }}</h1>

djangoProject/templates/sale_management/employee/index.html
{% if latest_employee_list %}
    <ul>
        {% for employee in latest_employee_list %}
         <li>
            <a href="{% url 'sale_management:employee_detail' employee.id %}">
                {{ employee.name }}
            </a></li>
        {% endfor %}
    </ul>
{% else %}
    <h1>No employee are avaiable</h1>
{% endif %}

djangoProject/templates/sale_management/order/detail.html
<style>
table, th, td {
  border: 1px solid black;
  border-collapse: collapse;
}
</style>

{% if order %}
    <h2>{{ order }}</h2>
    <table style="width:100%">
        <tr>
            <th>Id</th>
            <th>Product</th>
            <th>Price</th>
            <th>Quantity</th>
            <th>SubTotal</th>
        </tr>
        {% for item in order.orderdetail_set.all %}
        <tr>
            <td>{{ item.id }}</td>
            <td>{{ item.product }}</td>
            <td>{{ item.product.price }}</td>
            <td>{{ item.quantity }}</td>
            <td>{{ item.subtotal }}</td>
        </tr>
        {% endfor %}
    </table>
{% else %}
    <h1>No order are avaiable</h1>
{% endif %}

djangoProject/templates/sale_management/order/index.html
<style>
table, th, td {
  border: 1px solid black;
  border-collapse: collapse;
}
</style>

{% if orders %}
    <table style="width:100%">
        <tr>
            <th>Id</th>
            <th>Customer</th>
            <th>Purchase Date</th>
            <th>Delivery Date</th>
            <th>Employee</th>
        </tr>
        {% for order in orders %}
        <tr>
            <td><a href="{% url 'sale_management:order_detail' order.id %}">{{ order.id }}</a></td>
            <td>{{ order.customer }}</td>
            <td>{{ order.purchase_date }}</td>
            <td>{{ order.delivery_date }}</td>
            <td>{{ order.employee }}</td>
        </tr>
        {% endfor %}
    </table>
{% else %}
    <h1>No order are available</h1>
{% endif %}